### ISSUE TITLE
CodeGlimpse 0.0.1

### ISSUE THREAD

**Issue by stephan281094** [CodeGlimpse/CodeGlimpse#14]
### To do
- [ ] Create helper out of user data (instead of router param)
- [ ] Improve security (remove autopublish and insecure and create publications)
- [ ] Get 'follow'-feature working
- [ ] Get user avatar fully working (adding img url to db)
- [ ] Get feed page to show following users
- [ ] Get post creation/ editing working

### Done
Nothing so far
